### ISSUE TITLE
Unexpected end of input error...

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [moznion/gulp-tsd#6]
Hi,

I am running gulp-tsd and I get the following error:

    E:\source\gulp-tsd-spike\node_modules\gulp-tsd\node_modules\tsd\node_modules\blueb
    ird\js\main\async.js:93                                                                                        
                    throw res.e;                                                                                   
                             ^                                                                                     
    SyntaxError: Unexpected end of input                                                                           
        at Object.parse (native)                                                                                   
        at E:\source\gulp-tsd-spike\node_modules\gulp-tsd\node_modules\tsd\build\http\
    HTTPCache.js:131:39                                                                                            
        at tryCatch1 (E:\source\gulp-tsd-spike\node_modules\gulp-tsd\node_modules\tsd\
    node_modules\bluebird\js\main\util.js:63:19)                                                                   
        at Promise$_callHandler [as _callHandler] (E:\source\gulp-tsd-spike\node_modul
    es\gulp-tsd\node_modules\tsd\node_modules\bluebird\js\main\promise.js:695:13)                                  
        at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (E:\source\portal-angular\mercury\sourc
    e\resource\wbms\node_modules\gulp-tsd\node_modules\tsd\node_modules\bluebird\js\main\promise.js:711:18)        
        at Promise$_settlePromiseAt [as _settlePromiseAt] (E:\source\gulp-tsd-spike\no
    de_modules\gulp-tsd\node_modules\tsd\node_modules\bluebird\js\main\promise.js:868:14)                          
        at Promise$_settlePromises [as _settlePromises] (E:\source\gulp-tsd-spike\node
    _modules\gulp-tsd\node_modules\tsd\node_modules\bluebird\js\main\promise.js:1006:14)                           
        at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (E:\source\portal-angular\mercury\source\resour
    ce\wbms\node_modules\gulp-tsd\node_modules\tsd\node_modules\bluebird\js\main\async.js:74:12)                   
        at Async$consumeFunctionBuffer (E:\source\gulp-tsd-spike\node_modules\gulp-tsd
    \node_modules\tsd\node_modules\bluebird\js\main\async.js:37:14)                                                
        at process._tickCallback (node.js:419:13)                                                                  

In terms of versions, I am on node version v0.10.32 (also tried v0.12.0) and gulp version.

My gulp_tsd.json looks like:

    {
      "command": "reinstall",
      "latest": true,
      "config": "./tsd.json",
      "opts": {
      }
    }

and my tsd.json looks like:

    {
      "version": "v4",
      "repo": "borisyankov/DefinitelyTyped",
      "ref": "master",
      "path": "typings",
      "bundle": "typings/tsd.d.ts",
      "installed": {
        "jasmine/jasmine.d.ts": {
          "commit": "0d999bb4663ec3212427c0b0ff28fc08c065e98d"
        },
        "angularjs/angular-mocks.d.ts": {
          "commit": "bba33bcb0b363ae41db8517a09d1a4d07828616b"
        },
        "jquery/jquery.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angularjs/angular.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "moment/moment.d.ts": {
          "commit": "5fe6713e8b2a05652a11bd26932ca0345fbb65ed"
        },
        "angular-hotkeys/angular-hotkeys.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angular-ui-bootstrap/angular-ui-bootstrap.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angular-ui/angular-ui-router.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "typeahead/typeahead.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "angularjs/angular-resource.d.ts": {
          "commit": "1fb0d8c3e30156e69a86271d0532d68d71e0735c"
        },
        "restangular/restangular.d.ts": {
          "commit": "35fffaa44bff5392741b3022d805fe3563023a3d"
        }
      }
    }

**Comment by ShiraazMoollatjie** [comment]
I found my problem. Turns out that the ```tsd.json``` path needs to exist beforehand. Might be useful for someone since the error message is not indicative of the actual error.

**Comment by moznion** [comment]
Thanks for your reporting.
I'll consider about the error message which is pointed out.
